steps:
  # Install all dependencies, including devDependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  # Run test coverage
  - name: 'node:18'
    entrypoint: 'npm'
    args: [
      'run', 'coverage'
    ]

  # Portage to build your image
  - name: 'ghcr.io/easy-up/portage:v0.0.2'
    env:
     - "PORTAGE_IMAGE_PUBLISH_ENABLED=1"
    args: [
      'run', 'all', '--config', '.portage.yml', '--tag', '${_IMAGE_NAME}'
    ]

  # Deploy the application to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'doe-demo-api',
      '--image', '${_IMAGE_NAME}',
      '--region', 'us-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# Define the variables used in the build
substitutions:
  _IMAGE_NAME: "us-west1-docker.pkg.dev/shared-resources-gcp/shared-container-registry/doe-demo-api"

options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: 'gs://doe-demo-app-cloud-build-logs/doe-demo-api/'
    paths: ['artifacts/*.*']
